(()=>{var d=class{constructor(t){this.box=null;this.boxSize={width:0,height:0};this.rows=0;this.dataList=[];this.indexs=[];this.idMap={};this.avatar=!1;this.speed=20;this.height=36;this.gapWidth=20;this.gapHeight=20;this.delayRange=5e3;this.align="center";this.animates=new Map;this.stageAnimates=new Map;this.update(t)}_divisor(t){let a=.5;switch(t){case"half":a=.5;break;case"top":a=1/3;break;case"full":a=1;break;default:break}return a}_initBarrageList(){if(!this.box.querySelector(".barrage-list")){let t=document.createElement("div");t.className="barrage-list",t.setAttribute("style",`gap:${this.gapHeight}px;justify-content: ${this.align};display: flex;height: 100%;flex-direction: column;overflow: hidden;`);for(let a=0;a<this.rows;a++){let i=document.createElement("div");i.className=`barrage-list-${a}`,i.setAttribute("style",`height:${this.height}px;position:relative;`),t.appendChild(i),this.dataList[a]=[]}this.box.appendChild(t)}}_pushOne(t){let a=this.dataList.map(e=>e.length),i=Math.min(...a),s=a.findIndex(e=>e===i);this.dataList[s].push(t)}_pushList(t){this._sliceRowList(this.rows,t).forEach((i,s)=>{this.dataList[s]?this.dataList[s]=this.dataList[s].concat(...i):this.dataList[s]=i})}_sliceRowList(t,a){let i=[],s=Math.round(a.length/t);for(let e=0;e<t;e++){let h=[];e===t-1?h=a.slice(e*s):e===0?h=a.slice(0,s):h=a.slice(e*s,(e+1)*s),i.push(h)}return i}_dispatchItem(t,a,i){if(!t||this.idMap[t.id])return;this.idMap[t.id]=t.id;let s=this.box.querySelector(`.barrage-list-${a}`),e=document.createElement("div");e.className="danmu-item",e.setAttribute("style",`
					height:${this.height}px;
					display:inline-flex;
					position: absolute;
					right: 0;
					background-color: var(--trm-danmu-bg-color,#fff);
					color: var(--trm-danmu-color,#000);
					border-radius: 32px;
					padding: ${this.avatar?"4px 8px 4px 4px":"4px 8px"};
					align-items: center; `),e.innerHTML=`
					${this.avatar?`<img class="danmu-avatar" style="display: inline-block;width:${this.height-8}px;height:${this.height-8}px;border-radius:50%;margin-right:6px;" src="${t.avatar}">`:""}
					<div class="danmu-text" style="text-wrap:nowrap;overflow:hidden;text-overflow:ellipsis;">${t.text}</div>`,s.appendChild(e);let{width:h}=e.getBoundingClientRect();e.style.width=`${h}px`;let o=(this.boxSize.width+h)/this.speed*1e3,u=(h+this.gapWidth)/(this.boxSize.width+h)*o;if(i<this.dataList[a].length){let r=e.animate({transform:["translateX(100%)",`translateX(-${this.gapWidth}px)`]},{duration:u,fill:"forwards"});this.stageAnimates.set(r,r),r.onfinish=()=>{this.stageAnimates.delete(r),this.indexs[a]=i+1,this._dispatchItem(this.dataList[a][i+1],a,i+1)}}let n=e.animate({transform:["translateX(100%)",`translateX(-${this.boxSize.width}px)`]},{duration:o,fill:"forwards"});n.onfinish=()=>{this.animates.delete(n),e.remove(),e=null},this.animates.set(n,n)}_run(){let t=this.dataList.length;for(let a=0;a<t;a++){let i=this.dataList[a],s=this.indexs[a];!s&&s!==0&&(s=this.indexs[a]=0),i[s]&&setTimeout(()=>this._dispatchItem(i[s],a,s),Math.random()*this.delayRange)}}pause(){return this.animates.forEach(t=>t.pause()),this.stageAnimates.forEach(t=>t.pause()),this}play(){return this.animates.forEach(t=>t.play()),this.stageAnimates.forEach(t=>t.play()),this}clear(){return this.dataList=[],this.indexs=[],this.idMap={},this.animates.clear(),this.stageAnimates.clear(),this.box.querySelector(".barrage-list")&&this.box.removeChild(this.box.querySelector(".barrage-list")),this}update(t){let a=document.querySelector(t.el);if(a){let i=a.getBoundingClientRect();this.box=a,this.boxSize=i,this.speed=t.speed??this.speed,this.gapWidth=t.gapWidth??this.gapWidth,this.gapHeight=t.gapHeight??this.gapHeight,this.avatar=t.avatar??this.avatar,this.height=t.height??this.height,this.delayRange=t.delayRange??this.delayRange,this.align=t.align??this.align,this.rows=parseInt((i.height*this._divisor(t.mode??"half")/(this.height+this.gapHeight)).toString()),this.clear()}else throw new Error(`\u672A\u627E\u5230\u5BB9\u5668 ${t.el}`);return this}pushData(t){switch(this._initBarrageList(),Object.prototype.toString.apply(t)){case"[object Object]":this._pushOne(t);break;case"[object Array]":this._pushList(t);break}return this._run(),this}},c=new d(window.ASYNC_CONFIG.danmu);window.danMu=async l=>{c.update(window.ASYNC_CONFIG.danmu).pushData(await l()),window.ASYNC_CONFIG.swup&&document.addEventListener("swup:contentReplaced",async function(){c.update(window.ASYNC_CONFIG.danmu).pushData(await l())})};})();
