// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ArrayInput: (typeof import('./components/edit/ArrayInput.vue'))['default'];
		BaseInput: (typeof import('./components/edit/BaseInput.vue'))['default'];
		ChangeLog: (typeof import('./components/ChangeLog.vue'))['default'];
		ChangeLogs: (typeof import('./components/ChangeLogs.vue'))['default'];
		DemoSite: (typeof import('./components/DemoSite.vue'))['default'];
		DemoSites: (typeof import('./components/DemoSites.vue'))['default'];
		DemoSitesLine: (typeof import('./components/DemoSitesLine.vue'))['default'];
		EditConfig: (typeof import('./components/EditConfig.vue'))['default'];
		EditConfigArrayInput: (typeof import('./components/EditObjectArray.vue'))['default'];
		EditConfigItem: (typeof import('./components/EditConfigItem.vue'))['default'];
		EditConfigObjectArrayInput: (typeof import('./components/EditObjectArray.vue'))['default'];
		EditInputs: (typeof import('./components/EditInputs.vue'))['default'];
		EditObjectArray: (typeof import('./components/EditObjectArray.vue'))['default'];
		EnumInput: (typeof import('./components/edit/EnumInput.vue'))['default'];
		IconList: (typeof import('./components/IconList.vue'))['default'];
		InfoToast: (typeof import('./components/InfoToast.vue'))['default'];
		ObjectArrayInput: (typeof import('./components/edit/ObjectArrayInput.vue'))['default'];
		OutLine: (typeof import('./components/OutLine.vue'))['default'];
		SponsorsLog: (typeof import('./components/SponsorsLog.vue'))['default'];
		SwitchInput: (typeof import('./components/edit/SwitchInput.vue'))['default'];
	}
}
