// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    DemoSite: typeof import('./components/DemoSite.vue')['default']
    DemoSites: typeof import('./components/DemoSites.vue')['default']
    IconList: typeof import('./components/IconList.vue')['default']
    InfoToast: typeof import('./components/InfoToast.vue')['default']
    Sites: typeof import('./components/Sites.vue')['default']
  }
}
